# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
