# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
