# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0003_auto_20170727_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
