# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0004_auto_20170727_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
